### ISSUE TITLE
Photo Pics

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1028]
It seems if a pic is loaded in feed and then in photos but different images the photo names are not checked for duplicates in the Saved file so two images can have same file tag. Needs to be thoroughly tested.

**Comment by one44** [comment]
It has something to with title when using photo up loader and two images have same title.......

**Comment by Data66PF** [comment]
I have an image ladybug.jpg . I loaded it in the feed. Then I loaded it in the photo section. Both images have the name ladybug. I am not seeing any error with it. The script saves it as a random number in the server. It has never had a test to see if people are using the same named image though. It would be hard to change this because you could have two people in two locations that just happen to have a ladybug.jpg image, as an example, and one would be able to use it but the other wouldn't, if we changed the process. 

If that is your issue that is.

**Comment by one44** [comment]
When looking at the images with the images along the bottom it shows the different images but calls the same image as the last one uploaded. 4.2

**Comment by Data66PF** [comment]
I am confused a bit. Photos uploaded via status share do not go into the photo section. Only photos uploaded via the photo uploader go in the photo section and show in the little thumbnails at the bottom of photos. Do I need to only test in the photo section to upload images with the same name?

**Comment by one44** [comment]
Sorry not knowing how things work does make it difficult to explain but it seems you have the idea. What happened was is that I had two images in the bottom strip of the photo module that were identical but when I clicked on them a different image would show.Both were labeled img4 The original one no longer appeared but that is what was showing in the strip as both images.

**Comment by Data66PF** [comment]
Perhaps it was a cache issue? Is this still an issue in 4.2.2?

**Comment by neil96** [comment]
I tested with three different images with the same name. First image upload to main feed, and two images upload to photo (section). All work well and I didn't see any error.
