### ISSUE TITLE
Cloudflare issues

### ISSUE THREAD

**Issue by Data66PF** [moxi9/phpfox#1037]
Many of our clients, myself included, use Cloudflare in order to reduce spam hitting the server and it can speed a site. https://www.cloudflare.com/overview/ as this seems to be an increasing issue for clients, we need to fully test things and ensure our script works with it due to increasing spam activity. We are seeing theme issues now when using cloudflare.

**Comment by Gatsby-PF** [comment]
I have noticed an extreme slowdown in execution of theme called JS scripts in network console when page loading after 4.2 stable. Additionally, I have notice that the theme causes the browser to make a connection to Cloudflare for only a JS momemts script, a connection used only for IM module...even if the IM module is not used. It should only make the connection if a user enables the IM app.

Somewhat related and relevant:
Users of Tor Browser (I encourage ) will be blocked from accessing any site using Cloudflare all the time and captcha entery does not work, so this is normal and not a bug if someone here gets this using Tor. For that reason I cannot use Cloudflare, because I am a Tor supporter, and recommend my sites users to use Tor and Tails instead of direct browsers as their web browsing regime.

**Comment by Data66PF** [comment]
will close for now but we had complaints from clients.
