### ISSUE TITLE
Site not properly show in android phone

### ISSUE THREAD

**Issue by haisay** [moxi9/phpfox#1077]
![img_20160205_094024](https://cloud.githubusercontent.com/assets/12654556/12838898/55c8e27a-cbf9-11e5-9475-4c0f47f1c095.JPG)

I tried many time in reload.
in pc its ok.

I try to load url like www.mysite.com/mypage

v4.2
please check and confirm.

**Comment by optiroot** [comment]
Try clearing cache and/or rebuilding theme. Remember to save all edits you made to it.
Otherwise I had the same problem with a bad-written htaccess. If you are trying deny all connections but allow you, PHPfox has a strange behavior about this: doesn't block everyone, just doesn't show them the CSS.

So if you made something like this, this could be the problem.

I'm saying this because I don't have this problem, and I have custom-made Bootstrap theme with 4.2.1 - you can even try upgrading.

**Comment by Data66PF** [comment]
Please use 4.2.1 latest version. We cannot reproduce the issue on our staging, demo, local installs, live development site and the client above this comment also cannot reproduce the issue.
