### ISSUE TITLE
[v4.2.1] Theme Manager Issue - 2

### ISSUE THREAD

**Issue by Spaninet** [moxi9/phpfox#1091]
I set as default one of the bootstrap themes, and now when i access my site it loads with Neutron.*

*I haven't Netron before in Themes. I use v4.2.1b5

See #1086 #1087

**Comment by Data66PF** [comment]
I can't reproduce this. Can you please provide a screen shot in this bug report?

**Comment by Spaninet** [comment]
This is my site with the Neutron's old look (it's not the new Neutron based in Bootstrap).

![Screenshot](https://community.phpfox.com/file/attachment/2016/02/f86e72318231fab4da3d182cbc891fd8.png)

I've tried rebuilding the Core Theme but nothing changes.

**Comment by Data66PF** [comment]
Please follow this tutorial, https://docs.phpfox.com/display/FOX4MAN/Front+Visitor+Banners+Not+Rotating and revert theme for bootstrap in order to bring in any template fixes. Note that revert theme will remove all customizations to the bootstrap theme so be sure you make a backup first. Make sure, going forward, that you do not make any edits to default bootstrap theme or default bootstrap theme files. Note that for my own site, I removed any old theme files that I didn't need or any that didn't work in previous attempts to make themes when they made that redundant bootstrap theme. This seemed to resolve any issues and also removed that duplicated redundant bootstrap theme.

**Comment by Spaninet** [comment]
I've followed the tutorial but still the same.

I solved the problem by overwriting all files with the new ones from new package (zip file).
