### ISSUE TITLE
Using same label name (in phrases) for two total different items.

### ISSUE THREAD

**Issue by PhpFoxJohnJr** [moxi9/phpfox#1095]
This is confusing to the users.

You are using the same single phrase for two different areas under the user profile page.    Next to Profile menu and Friends menu there is three dots (which is only one less character then the word "more"  but anyways.  When you click on that if the user has any **Pages** then it will say pages and the number of **Pages** the owner owns.

Now below that on the left column there is a block that says the same thing...**Pages** but this is not the **Pages** the profile owns but instead how my **Pages** the owner likes/follow.  So this is very confusing for users and the bottom one should say something like Pages Followed or Following or something else :)

![pagephrase](https://cloud.githubusercontent.com/assets/14913734/12874758/48dc0ba2-cda0-11e5-991f-5a57a9484867.png)

**Comment by neil96** [comment]
Block Pages (left side of image) list all pages you created and liked, Menu Pages (right side of image) only list pages you created. Experience  user will clear it.

**Comment by PhpFoxJohnJr** [comment]
Didn't see it is liked and pages created...still confusing but you have too many other issue to fix than to worry about this...guess I was worried about new users.

**Comment by Data66PF** [comment]
I suggest changing the phrase for the followed ones to be Following/Joined.

**Comment by PhpFoxJohnJr** [comment]
Thanks data...neil96 response "Experience user will clear it." seemed kind of lame to me since it took me more time to do up the picture and edit the picture and post the bug than it would take to change the variable in the code and give a new phrase for that variable so if someone wanted to change it they could.  Wonder if they realize in the real world companies pay/hire people to test and find bugs/errors and we put our free time to help them solve their problems with their product.  Please remind them of that as I used to just hack the code and fix it myself and not tell them.  In my 3.8 version I have over 156 hacks to make it work they I want it (that includes add-on as well).

**Comment by neil96** [comment]
We will change the phrase of the block on left site.

**Comment by PhpFoxJohnJr** [comment]
Thank you.  I know I seem snobby some times...but I am only trying to help :)

**Comment by Data66PF** [comment]
@PhpFoxJohnJr thanks for your help and please remember that I am part of "them/they" when I post :) Our team is very good with fixing the code but as coders, they see code. My part of the team here is to be the client voice to make sure it is more clear as to why you or others have an issue with things so that our great coders can improve things for everyone. It takes a village if you remember that term. :) Our phpFox is a village of great folks coming together to make this script the best it can be. Clients, third party devs, core developer coders, QC, me :) plus more staff for backup in general. 

Some things posted can be fixes implemented fairly easily and so they get the Enhancement label and we implement some of those for current releases. Other fixes might need to be put off until later in the process or for more discussion. We do plan on a feature request area for these sort of things so we can keep our "bugs" away from our "feature wishes" in order to fix bugs faster as enhancements slow us from fixing broken things.

As such, sometimes you might post things that we close and say, please post in the forum or please wait for us to open the feature area. Hope you understand our position. Glad this is being resolved for you though. :)

**Comment by neil96** [comment]
I changed the phrase on the left side.

**Comment by PhpFoxJohnJr** [comment]
Thank you neil96
