### ISSUE TITLE
Sponsored block width not consistent with other blocks

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#1106]
Issue with sponsored block width not correct size. also sponsored (Title) is not lock the other blocks.

![2016-02-09 4](https://cloud.githubusercontent.com/assets/14006326/12930989/7ea5d5ce-cf49-11e5-8da7-eb72db8b8698.png)

**Comment by Data66PF** [comment]
Sponsored block has always done that in order to differentiate the ads from the content blocks. Perhaps we can look at it but then we will have other clients complain as they prefer it like that so it's a difficult call to make when some like it and some don't.

In regards to the size, I cannot reproduce this in 4.2.2 default bootstrap or neutron themes.
