### ISSUE TITLE
music album cover

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1126]
when viewing a music album the cover image is white. in website sourcecode the image path in data-src is right but in src it looks like src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7". the image does not show up. tested with win 7-10 latest and some older ff. on dev, live and stage.phpfox.com. in internetexplorer 11 the image shows up. edge not testetd yet...

**Comment by neil96** [comment]
Did you disable javascript?
Did you see image url on data-src? We put image url on data-src, when the site loaded, we update that url to src. If you disable javascript on browser, it will not work.

**Comment by lordofnos** [comment]
yes image url is in data-src. javascript is enabled.

**Comment by lordofnos** [comment]
strange... when browsing album the data-src has the same values but the image is showing. btw this is tested on different computers at different locations.

**Comment by Data66PF** [comment]
As our v4 demo site is updated, I looked there. https://v4.phpfox.com and I see two that show as no image https://v4.phpfox.com/music/browse/album/ can you try using a different image for the album cover to test as the others all show up, making me think it is an issue with the image being used.

**Comment by lordofnos** [comment]
on my site its on all albums

difference between browse and album view in sourcecode:

browse:
alt="albumnae"  itemprop="image"  class=" _image__120_square image_deferred "

album view:
alt=""  class=" _image_200 image_deferred "

could this cause the issue?

**Comment by lordofnos** [comment]
class seems not to be complete ;)

**Comment by Gatsby-PF** [comment]
May I remind the court of this identical issue which is now closed due to failure to reproduce by others.
https://github.com/moxi9/phpfox/issues/771
Until now.
As of 4.2 I no longer experience this issue.  The music album cover is showing up normally due to no intervention of my own.

**Comment by Data66PF** [comment]
In your example of the class, one is using the old square method and the other is using the newer non-square image. We had (or have, I've not checked yet) the setting to keep non square images. If that setting is at false, and then we don't have the non-square images made, then the newer code (I say newer as it was added in V3 as optimization) won't work since we now don't have a non-square image.
core.keep_non_square_images

Do you have a current link to the https://v4.phpfox.com demo where you have an album cover for us to see it please?  Can you also attach here the image you are testing with?
