### ISSUE TITLE
Homepage banner problem (important issue)

### ISSUE THREAD

**Issue by karargaht** [moxi9/phpfox#1127]
Photo featured and homepage banner mess

**Please watch the video**

https://www.youtube.com/watch?v=KlJ8Ln5Ox8o

**Comment by Data66PF** [comment]
don't see any mess. Please see how the home page banners work. https://docs.phpfox.com/display/FOX4MAN/Changing+the+Visitor+Home+Page+Background+Image  

If you don't want to see the featured photo as one of the front banners, you need to upload a banner as shown. Otherwise, it is designed to cycle through featured photos if there are featured photos.
