### ISSUE TITLE
Registration with profile image Upload failed. Your file (1023 kb) is larger then our limit: 500 kb

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1172]
Registration with profile image Upload failed even when settings are at 2000.
http://prntscr.com/a8i5ti

user group settings for profile image: http://prntscr.com/a8i4bp

Photo settings: http://prntscr.com/a8i4wj

**Comment by Data66PF** [comment]
Did you check your server settings for file uploads? Did you check settings for Guest group since it is a Guest that is registering and not a Registered user?

**Comment by neil96** [comment]
In this case, you have to change settings on user group guest. I know you will confuse. You have to change settings on user group guest because:
- When registering, user still is guest, all user group settings, we still get value of guest user.
- We don't get value of registered user because: admin can enable subscribe, and we can't know which user group of user after register.
