### ISSUE TITLE
Users Cannot remove post from others on their own profile need fix asap

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1208]
Cannot remove post from others on own profile. We need a fix for this ASAP as people can run a muck of things because people can't delete what someone else post on their profile.

**Comment by Data66PF** [comment]
is the user group setting set to allow it?

**Comment by lueung** [comment]
yes this occurs after the v4.3 update

**Comment by Data66PF** [comment]
Did you click the Options icon and select Delete? It is working for me on my admin user. Will go log in with a registered too though.

**Comment by Data66PF** [comment]
Confirmed. We need to fix this as we have it tied to this setting:

Can delete other feeds?

That setting is to delete any feed on the site. We cannot tie it to that setting. It needs to remain its own setting for this one:

Can remove feeds from their own profile?

So, please fix it so that when Can remove feeds from their own profile? is at True, it works for that user group to delete a feed on their profile as that setting was intended so that users can delete stuff on their profile but not be able to delete stuff in the main feeds area. 

It does not rely on Can delete other feeds? as that setting is to delete feeds all over the site and should be able to be at No for the user group and still allow them to delete from their profile if the other setting is at True.
