### ISSUE TITLE
Deleted member still have a profile

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#1241]
latest phpfox with bootstrap
 Deleted members are still showing in  New Members block (even after clearing cache) . They  have a profile link . we can add them as friend  . poke them etc.

**Comment by Data66PF** [comment]
So it is not just with the block itself but they have an actual link and can be poked, etc on their profiles?

**Comment by aakash83** [comment]
yes . i can access their profile .poke them add as friend etc

**Comment by Data66PF** [comment]
When you delete them in AdminCP, which method are you using? do you click the drop down next to the user image and select Delete, or do you click the checkbox and then click the delete at the bottom of the page?

**Comment by Data66PF** [comment]
Odd because my New Members block that I made and is in the store is not showing deleted members for me. I just tested it. So I don't know if you have a different one or if something is odd with your site or maybe you had members that were duplicated (made more than one account).

I then tested deleting the users and they all deleted. I cannot reproduce any issue.

**Comment by aakash83** [comment]
duplicatess . sooryyy
