### ISSUE TITLE
Reports are Non descript

### ISSUE THREAD

**Issue by lueung** [moxi9/phpfox#1245]
Viewing reports are a bit confusing and non descript. It looks as if the person doing the reporting is being reported. 
![screenshot_1](https://cloud.githubusercontent.com/assets/17013208/13998792/6e44d8a0-f10f-11e5-8c91-a4eb7186c620.png)

**Comment by Data66PF** [comment]
![report](https://cloud.githubusercontent.com/assets/6908282/14018438/2f483dbe-f1a4-11e5-8c07-17cae5152090.png)

This is working as it is designed for most of it. The first column is for the module that the report is for. If you click the link, it takes you to that item being reported so that is fine.
In my image, you can see that the user (me) added feedback text so that works fine.

The only issue I see that we should fix, which you could fix now if you need it sooner, is in the Phrase for Last-Report. It really should be phrased to show that it is the name of the user reporting the issue. Perhaps "Reported by" or "User Reporting". I'll mark a bug for us to fix the issue with the phrase.

If you want other things changed, please add a feature request.

**Comment by neil96** [comment]
Fixed on 4.3.1
