### ISSUE TITLE
cropping tool auto save

### ISSUE THREAD

**Issue by SalmanKhan86** [moxi9/phpfox#1250]
In admin cp when we enable option to (Force users to use the cropping tool before completing the profile photo upload routine) is not working.its automatically save photo when user upload it.
does't verify whether user crop photo or not.
photo must be saved after user crop and click on save avatar.
check it on v4.3.0

**Comment by Data66PF** [comment]
I can confirm that if I set the setting to True, I can then upload a profile pic and can leave the  upload page after it loads and without cropping and the image loads without the crop. I think we need to remove this setting though as we have a set size now for profile photos anyway and so that setting, which was to make a uniform size, isn't used.

**Comment by SalmanKhan86** [comment]
User Must be forced to crop photo with out this he will not able to upload it like this Always happen in fb and twitter.there is reason behind it.Suppose user upload a part of photo he don't want to show to real world and want to crop a part of it in application.so this is required here.

**Comment by optiroot** [comment]
Cropping and selecting a part of a photo that an user wants is a must. So there is no reason to remove this, because the thumbnail could be loaded by phpFox randomly.
If I upload a long picture, the thumbnail will get my stomach. So this feature is a must.

**Comment by SalmanKhan86** [comment]
yes this feature is must.
