### ISSUE TITLE
Force HTTPS for Logged In Users doesn't switch successfully 

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1275]
Does not successfully switch to https when logging in so user is stuck at the login page unless the manually type in https.

**Comment by Data66PF** [comment]
this setting requires that you also set admincp/setting/edit/?group-id=server_settings , Secure Pages with HTTPS and has always required that to be set. However, we seem not to have that notice shown in the setting and for some reason, we have the Secure Pages with HTTPS in Server Settings instead of in Security where the other setting is. We should move it to Security so they are both together and for the Force HTTPS for Logged in Users, we need to put the phrase that it requires the other setting to work. Marking a bug due to the confusion with the setting.

**Comment by Gatsby-PF** [comment]
The server should also be set to force https connections independent of phpFox settings.

**Comment by warain** [comment]
short url worked well on my site, but today after I turned on force https, on the AdminCP side, I can no longer log into my site, pages like https://medted/user/login are returning not found
