### ISSUE TITLE
On blogs photo attachments do not set item_id in attachment table.

### ISSUE THREAD

**Issue by phpFox-webwolf** [moxi9/phpfox#1349]
On blogs photo attachments do not set item_id in attachment table.  This may be caused by no val[attachment] being returned upon submission.  This causes there to be no connection to the blog item and results in orphaned files and db entries when blogs or users are deleted.   

File attachments seem to be okay.

**Comment by phpFox-webwolf** [comment]
The same problem occurs with forum posts.

**Comment by Data66PF** [comment]
To our core devs, please look into this for our optimizations as it is making HUGE file issues for clients unable to manage attachments once a user deletes their account, all other data is removed but all abandoned attachments remain on the server.

**Comment by neil96** [comment]
By default, we don't set item_id for inline attachments, because inline attachments can use any place on your site. If we set item_id for these attachments, it will delete when a parent item is deleted. 
To resolve this issue, I create a page to manage attachment. On this page, it will display all attachment was added. You can delete them if you think it don't use anymore.
