### ISSUE TITLE
Categories selection still showing photos

### ISSUE THREAD

**Issue by jrann** [moxi9/phpfox#1378]
Even though you set Allow Selection of Categories to NO. in photos.
the category selection stills when uploading a photo.
PHPFOX v4.3.2

![category issue](https://cloud.githubusercontent.com/assets/18630247/14783231/cf5e77a4-0b31-11e6-9728-0b675079d71c.png)

**Comment by Data66PF** [comment]
This is working as designed. The option is for when uploading a photo. If you go set it to True and test, you will see an option under the upload box for categories. If set to No, that option is not there.

The setting was never made to control whether a user can use categories after upload, which is what you are showing.

In order to change this, please file a feature request as this is how the script is designed to work.  There is no setting at this time to control whether users can assign categories after upload.
