### ISSUE TITLE
video app does not load more than 12 videos

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#1394]
when scrolling down, the video app does not load more videos. since old versions do not work anymore it may be a problem with feed module or some other improvements with 4.3.2 build 3. tested on own site and v4.phpfox.com

**Comment by Rodios** [comment]
I have the same issue

**Comment by sammern** [comment]
Me too

**Comment by ashdelacroix** [comment]
I'm thankful that this bug has been put onto the radar. I can confirm that since upgrading to 4.3.2 build 4, the Video app home page only loads 12 videos. On some sub-pages, such as My Videos, the lazy-loading actually works correctly and loads all relevant videos. So the bug appears mainly to affect the Video app home page.
