### ISSUE TITLE
Default Guest Permission AdminCP Block Layout

### ISSUE THREAD

**Issue by darksolar1** [moxi9/phpfox#1420]
Default Guest Permission: Can view block layout for themes within the Admin Control Panel? is set to Yes

**Comment by Data66PF** [comment]
I don't consider this a security issue. I've tried everything as a guest to see the block layout, including the old v3 link to it and every time I try a direct url, I still get redirected to the login screen and cannot see anything.

I'll confirm that the setting should be at false, but for anyone looking, this issue doesn't appear security related due to the requirement to log into admincp before anything can be seen.
