### ISSUE TITLE
photo can be seen by anybody

### ISSUE THREAD

**Issue by vizruta** [moxi9/phpfox#1451]
phpfox : V4
browser : all

Below are the settings done in my site 

1) admincp > tools > settings > site settings > friends only community > ''NO''

2) admincp > tools > settings > module > feed > friends only > ''YES''

when the serial no.2 settings is done perfectly then i guess the ''photos''  section should not be displayed to users in entire website. i guess it is a bug which is letting the entire users in the website to access the photo section. though an user can restrict from their privacy setting but serial NO.2 is global setting hence it should avoid rather than one has to restrict personally from privacy setting.

**Comment by Data66PF** [comment]
In order to have the photo section not viewable by everyone, you need to set your # 1 to Yes. Friends Only Community sets the items to Friends Only Privacy and will not show stuff to guests. This is a global site setting and not only for the Photo section though.

The item # 2 , Friends Only Feed is just for the main feed of the site and only controls feed items in the feed. It does not control items in the site itself.
