### ISSUE TITLE
AdminCP Search

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#1474]
Cannot test on demo site but if you enter a state in search in admincp it does not reset after search is done so every search has that variable in the search unless you remove it before each search.

**Comment by one44** [comment]
I do not understand??
![2016-06-21 10_53_09-admin cp _ search members _ bdsm dating bdsm social dating swingers dating for](https://cloud.githubusercontent.com/assets/13656046/16223769/3fe73c56-379f-11e6-88f4-cb265b2bcaad.png)

**Comment by Data66PF** [comment]
I'm referring to back end. Many times, I have to search for various things in the user search. I don't want to have to keep setting the country to search for all men or all women for example so it's handy. If I need to reset that, without clicking a new one, I click Search on the left menu and it will reset/clear all search stuff. Otherwise, it holds the search criteria in case that same criteria is needed again.

**Comment by Data66PF** [comment]
Please file a feature request to change this as some like it and some don't.
