### ISSUE TITLE
Blog Categories

### ISSUE THREAD

**Issue by MBonner702** [moxi9/phpfox#148]
Whenever you edit a blog, you have to choose the category all over again. Is this on purpose?

**Comment by GloriousKoch** [comment]
I believe it is there to change if you made a mistake in the first submission.

**Comment by MBonner702** [comment]
I understand the need to be able to change it but it removes the category you chose every time you go to edit it.
Thank you for your input, however. Support doesn't seem to be very active lately.

**Comment by GloriousKoch** [comment]
If you save it in the edit screen while it's "blank" does it remove the category entirely, or does it leave it the same?

As for the support, I have a feeling they're just taking a weekend break. I would say that the current release labeled as "stable" was a bit of a jump as this issue forum shows. It seems rather buggy and incomplete still and I know the main dev here has been working hard on it, so no complaints otherwise.

It's also given us a chance to form our own little "community" if you will of support to try and help each other with things we learn while attempting our own little patches and fixes, haha.

**Comment by Data66PF** [comment]
I tested and the category remains the same if you don't select a different one. It's just a tad confusing as it doesn't show the checkbox nor does it show "this blog is in x category, click below to change it" or some such thing.
