### ISSUE TITLE
Poll extra option added inbetween is not saved.

### ISSUE THREAD

**Issue by dhanyashree91** [moxi9/phpfox#1669]
While creating a poll, if I add a option by clicking '+' symbol in between(for example after the 1st option) the answer is not saved in the DB. However the option which are appended at the end are saved. 

Reproduced in the live demo site for reference.
https://v4.phpfox.com/poll/3/test-poll/

**Comment by Data66PF** [comment]
Confirmed.
Core Devs:
I note that we can add the poll 2 (for that test poll) at the bottom and move it up into position and that works fine. However, we have the + in between each one and so we either need those + to work or to remove the extra + and only leave the bottom one since a user can easily drag them up into position. IMO, all of those extra + are not needed.
