### ISSUE TITLE
[Photos Page] Thumbnail Size Off?

### ISSUE THREAD

**Issue by GloriousKoch** [moxi9/phpfox#181]
I'm assuming due to the design of the page in, next to each other, block form, that photo pages are meant to have same size thumbnails to keep the page in order? If it's not could we get an option for this? Here's some pics of what I mean...some of the pics are in line then a few aren't resized to the same size and makes the page look off.

![image](https://cloud.githubusercontent.com/assets/6254165/8822570/5ae2fee6-3034-11e5-8c61-3c3b6cf2b71d.png)

![image](https://cloud.githubusercontent.com/assets/6254165/8822571/5d8a38a8-3034-11e5-8bf4-1a4dafd84e83.png)

![image](https://cloud.githubusercontent.com/assets/6254165/8822574/61a5d4d8-3034-11e5-9e3a-6eecacfff878.png)

**Comment by Data66PF** [comment]
Did you set the setting for autocrop photos?

Note that I just noticed the setting is missing for autocrop photos.

http://community.phpfox.com/photo/ it is hard to see the photos as there is no spacing if we are using a grid layout of thingy.

**Comment by Data66PF** [comment]
Confirmed.

**Comment by RaymondBenc** [comment]
This is currently theme based and is designed after [Flickr](https://www.flickr.com/explore)

I'll add spacing between the photos as it is currently a little cramped. For those that want it to be more like Facebook, where it has square images, this needs to either be a theme or app. App might be the better solution since it will then work on all themes.
