### ISSUE TITLE
utf 8 problem

### ISSUE THREAD

**Issue by zx500** [moxi9/phpfox#248]
in v4 (last version)
arabic language have problem in  database and character in database saved like this Ø¨Ù‡ØªØ±ÛŒÙ† Ø³ÛŒ Ù¾ÛŒ ÛŒÙˆ  . and make our database huge . fix this problem please

**Comment by RaymondBenc** [comment]
Is it outputting incorrectly on your site?

**Comment by zx500** [comment]
yes output is correct but data in database saved incorrect ( i think they are coverted to Unicode) its make our data base huge after a time . i tested Arabic and Persian languages . fix this problem please

**Comment by comemoreru** [comment]
I also have this problem.

**Comment by Data66PF** [comment]
Not sure it's a bug but we have two that can reproduce it so it needs looking at to determine if it is a bug or not.

**Comment by neil96** [comment]
At this time this isn't a bug and how the product is designed. We would need to make a major change in order for this to work for specific clients and its risky at this point.

**Comment by neil96** [comment]
@RaymondBenc said: 
>At this time this isn't a bug and how the product is designed. We would need to make a major change in order for this to work for specific clients and its risky at this point.

**Comment by zx500** [comment]
this problem not fixed and i dont know why dont you want to fix  this

**Comment by optiroot** [comment]
Sorry but I don't think it is right for them,  Neil and Raymond! Because the problem that they're having is that letters and more are not saving as they should and their database is enlarging more than it should. 

This isn't really a bug, but it could be considered in this way if you think to the fact that phpFOX must be globally usable, this is a "block" for who doesn't uses UTF-8 characters.

Please open this issue and sign it as a bug, not because it really is, but because I think is better make phpFOX usable by everyone and in this case particularly.

If the database is enlarging as they say, this is a problem and even if you can't fix this easily (I know that's hard to solve this problem due to the nature of phpFOX) I think that is unrespectful don't mind the problem of these clients or developers. 

I don't have this problem, but I think is better for people, even if the fix will come in months and not now, that it is signed as bug. 

Think at it. 
Thank you!

**Comment by neil96** [comment]
Thanks very much @optiroot . We will note this issue and improve it when all bugs fixed.
