### ISSUE TITLE
Problem with displaying Message recipients names 

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#260]
If we send  a group message to  a lot of members e.g 10, then their names are not properly displayed . as shown in screenshot below
![image](https://cloud.githubusercontent.com/assets/406030/9068721/6e471056-3ae5-11e5-8e9f-a10fb60a186e.png)

**Comment by Data66PF** [comment]
I can't reproduce this. What is your screen resolution?

**Comment by aakash83** [comment]
it is not dependent on screen resolution. i tried all possible resolution options and it remains same.

**Comment by Data66PF** [comment]
Ok was it after sending? I didn't want to bother real people by sending a test on the phpfox website.

**Comment by aakash83** [comment]
actually i did not sent that message. i received it from somone.

**Comment by aakash83** [comment]
Also this horizontal scroll bar is appearing in this panel.
![image](https://cloud.githubusercontent.com/assets/406030/9093554/013635c8-3bad-11e5-861d-95956df31ec3.png)

**Comment by Data66PF** [comment]
The original issue of the usernames when sending to a bunch of users is confirmed. We only confirm one issue per bug report.

**Comment by aakash83** [comment]
@Data66PF @RaymondBenc i am feeling sorry to say this. You should be thankful to us that we are helping you to identify bugs .This is not an open source product we purchased it and by fixing these bugs you are not doing any favour for us.It was supposed to be bugs free. You are paying more attention to these minor things(one bugs two bugs etc) rather than fixing these bugs. Lot of times you just close issues posted by users just because you cannot reproduce them on Your end and don't bother to check it on multiple platforms.  I understand that bugs are also a part of software development process and it happens to almost every product. But there should be a proper software testing procedure for PHPfox so before releasing any new version it should be properly tested . which we unfortunately don't have. and this script is full of bugs.  Even most of times   raymond  don't mind when we post multiple bugs in a single issue. but sorry to say you always have this problem and you even don't care whether the second or third posted bug is fixed or not and just close the issue. Due to this behaviour a lot of bugs posted months ago are still not fixed. Please accept my apology if something makes you angry. Thanks

**Comment by Data66PF** [comment]
It doesn't make me angry. I test things, he tests things. I don't fix things. I marked this a bug. There are hundreds to test and I can only do so much on my own WITHOUT PAY. I'm trying to help as much as I can but it is easier to test when there is one issue per report as some issues are NOT bugs and so I either close the whole thing or say, I see this is an issue and mark that ONE issue a bug.

Thanks for posting bugs. Please keep them one per report to make it EASIER for the two of us. Otherwise, it is just taking far too long to figure these out as multiple issues are also confusing to try to sift through.

I hope you can see my side of things here.
