### ISSUE TITLE
Url rewite issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#292]
When i enabe short url option in admincp and update htaccess old photos that comming with v3 cant showing. When i try access to public_html/file/pic/ photos im getting "{"error":404}" error.
That is valid for all file folder content.
And please note its upgraded site from v3 its not about public_html/PF.Base/file!

![download 1](https://cloud.githubusercontent.com/assets/8562514/9140569/8155eefc-3d32-11e5-8eea-e9f03f238c82.png)

**Comment by Data66PF** [comment]
Are you using the new default .htaccess file with nothing extra added to it? The old .htaccess won't work with this.

**Comment by Data66PF** [comment]
Checking the client's site, I see open_basedir is enabled and PHPfox does not work with that setting, it never has worked with that enabled. Will see if disabling that solves the issues here.

**Comment by Data66PF** [comment]
Client asked to submit ticket to have Ray check the issue. This site had rename photo enabled before upgrade. If I recall correctly, it also has https enabled.

**Comment by RaymondBenc** [comment]
@Data66PF  @Anna3anana  have you come across the ticket ID#?

**Comment by Data66PF** [comment]
I don't see it. Perhaps it was closed by mistake?

**Comment by Ylmzef** [comment]
It's fixed after this: http://blog.phpfox.com/2015/08/11/short-url-rewrite-rules-for-fastcgi-servers-updated/
But my server run on suphp, I need to make changes?

**Comment by RaymondBenc** [comment]
Issue should now be fixed as the changes provided in the blog are part of the core product.

As for using suPHP, there is nothing wrong with it and is a good measure of extra security. The only issue that may arise is when installing apps/themes since the product itself installs the script, suPHP would change the permission of the files/folders to "nobody". You will then not be able to edit themes or update the products because the script would lose the permission on these files.

**Comment by Ylmzef** [comment]
When i enable FastCGI on server im getting "Uncaught SyntaxError: Unexpected identifier" error top on the newsfeed.
Also "No input file specified" for admincp.
