### ISSUE TITLE
v4  installation

### ISSUE THREAD

**Issue by clarkyu** [moxi9/phpfox#3]
I downloaded v4rc1 from github and following your instructions to install it. Here I have 2 questions:

1. I entered my License ID and Key as showed in my account but they didn't work. I have to try "techie" and it works.

2. After keying all details about database, it shows blank rather than a really installation.

**Comment by juggalobook** [comment]
1. That's what the instructions say to use. Not your real license information.
2. I had a blank white page also after step 2 inserting my database information, it never made it to step 3 where you add in admin details.

In the last part of the read me, it states to create a debug file so that it will spit out the error it is upset about. 

create the file:  PF.Base/include/setting/dev.sett.php

...and put the code:

<?php
define('PHPFOX_DEBUG', true);
?>

I didn't spend a lot of time after this on my install so I have not resolved the blank white page yet. but this may help you get yours working. I assumed since I was using nginx/php-fpm it might not like that so I was going to setup apache and see if it behaves better.

Good luck, if you resolve your white page, please share the fix that worked for you

**Comment by phpFox-webwolf** [comment]
I had the white page before creating the admin.  It turned out to be a use of mb_substr in the parse input file, which was not supported by my php.  I temporarily changed mb_substr to substr for installation purposes and then changed it back after downloading the appropriate php package.

**Comment by vluzhentsov** [comment]
phpFox-webwolf  - could you give more details on that issue? Identify the file, please.

**Comment by phpFox-webwolf** [comment]
Yes, the file name was input.class.php, (path include/library/phpfox/parse/) The line number is 197 or so.
The function also exists in url.class.php(799), but it's existence is verified first in this file before it is used.
It is also used in class.phpmailer.php(1617) and /default/class.phpmailer.class(1367)

**Comment by vluzhentsov** [comment]
Thanks. I will try.

**Comment by paolspo** [comment]
I installed version 4.0.1 but can not do anything can't  login and had this text: (no input file specified) any help please
thank you
