### ISSUE TITLE
The button Save in "Edit this page" doesn't work

### ISSUE THREAD

**Issue by picavizu** [moxi9/phpfox#30]
I tried to delete the Powered By using the "Edit this page" option. But when i save the page, nothing change. Actually, Meta Keywords, Meta Description, Custom Header, nothing really is saved.
I tried with chrome, Mozilla and Explorer. (V4)

**Comment by RaymondBenc** [comment]
What page are you trying to edit? I tested it locally on my install and after I hit "Save" I had to refresh the page to see the changes. Once refresh, do the changes not show up?

**Comment by Data66PF** [comment]
I'm having the same issue on a "live" dev site (on a server). I don't see issues specifically for this in dev console, however, I see a bunch of errors for font-awesome (on the blog page) in firefox latest version on win 8.1 but I don't think those are causing it not to save. It shows an odd thing when trying to save the title (as that is what I am testing). It shows it for admincp rather than for the blog page I'm editing (in the browser console). This is when front end on the blog page for testing this issue. 

Same issue is seen on the user browse (member) page.

**Comment by jameskenney** [comment]
When I go to Admin > Pages and click on a page, say Terms of Use, I'm taken to the edit page. I change the body of the page and click save. I'm taken to the page that was just edited with an error message that says "Page is missing data." I've tried using plain text in the body and html.

I'm using 4.0.0rc2(build 1436288901)

**Comment by RaymondBenc** [comment]
@jameskenney that specific issue should now be resolved in this repos build, however not in the public repo. That fix will be pushed there later today.

@Data66PF testing it on your dev site

**Comment by Data66PF** [comment]
This is working with the latest version.
