### ISSUE TITLE
HTTPS Mixed Content Errors

### ISSUE THREAD

**Issue by jason1234h** [moxi9/phpfox#37]
I'm getting mixed content errors on a stock installation of PHPFox 3. There's no theme or style other than the base model. Some pages will work (like PHOTOS) but most of the site fails to work and there is not lock.

**Comment by RaymondBenc** [comment]
If HTTPS works on some pages the general outlook is that it works with the product. If certain pages don't work it would be due to that some resources such as images or a CSS file is not loading via that protocol. We can't help much here unless you can provide the URL to your site so we can double check what resources are causing the problem. Feel free to [contact us](http://www.phpfox.com/contact) via our site and let us know your sites URL. Make sure to mention this bug report. I'd be happy to give it a look.

**Comment by jason1234h** [comment]
Thanks. I managed to get everything working. Actually, it was because I hadn't allowed enough time for the ssl and dedicated IP to propagate.
