### ISSUE TITLE
Html issue in old forum posts

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#377]
I upgaded from v3 to v4.
Now i see html codes insead bbcode in news feed.

Like this:
![download 2](https://cloud.githubusercontent.com/assets/8562514/9360847/eb4d6834-4698-11e5-9c41-c5ebadfcb6a3.png)

And when i try edit post in forums:
![download 3](https://cloud.githubusercontent.com/assets/8562514/9360888/1dbf5c6e-4699-11e5-97c8-46f1a6ef6380.png)

**Comment by Data66PF** [comment]
Html in the feed or any sections is no longer supported as mentioned in a few other issue reports and in the free app. However, if you want to use the setting (which is not recommended as it can be vulnerable to hacks) you can use the free app for that. http://store.phpfox.com/product/846/allow-html

**Comment by Ylmzef** [comment]
It's not html if you can check my second image it's bbcode from attachment photo on forum post.
But its showing html in news feed.

**Comment by Data66PF** [comment]
Yes because html does not work in the news feed.

**Comment by Ylmzef** [comment]
You don't understand.
I dont have any html codes in forum post. I have bbcode in forum post but i see html code in news feed.

**Comment by Data66PF** [comment]
You are not listening though. When a post goes to the feed, it is in code. Code in the feed is NOT supported. In order to have code showing in the feed, (which is not a good idea as it can make the site vulnerable), you need to use the free html app that allows code to show in the feed like it did with the allow html in feed setting before. This is how it works. If you post something in the forum, in a blog, etc, and it has html tags or bbcode tags or whatever code tags, it will show as straight code, it will not convert to an image. Try the free app or get a developer to change how it works. Ray even answered you about this before already. https://github.com/moxi9/phpfox/issues/212

**Comment by Ylmzef** [comment]
BBCODE img tag showing photo in news feed.
Check this:
![wez9dic5lthuwaaaabjru5erkjggg](https://cloud.githubusercontent.com/assets/8562514/9372670/87602df4-46e1-11e5-9226-02383c64f9d9.png)

**Comment by Jinkers** [comment]
@Ylmzef When you install the app, in the app's settings there is an option about which tags you allow to be used. Simply don't include the HTML tags.

**Comment by Ylmzef** [comment]
It's not good solutions this a bug and need be fixed.
I don't like using  third-party apps/modules.

**Comment by Ylmzef** [comment]
Also old status updates showing <br />
In status updates place of line break.

**Comment by Ylmzef** [comment]
This still issue for my old feed posts..

**Comment by Ylmzef** [comment]
@Data66PF @RaymondBenc I'm still waiting for solution for this since 19 august

**Comment by Data66PF** [comment]
This is a closed issue as html is not allowed on the site unless you use an app for it.

**Comment by Ylmzef** [comment]
Please install phpfox v3 and post some status within entering in status message etc.
Than upgrade to v4 than you can see there html code in the status posts.
This nothing to do with app etc. I cant use the app i dont want allow html on my site.
This issue for upgraded sites you can't close the ticket.

**Comment by Data66PF** [comment]
Our lead developer had already answered about this, https://github.com/moxi9/phpfox/issues/212 , the reason the code shows now is because html was disabled. With that disabled, then the code would show instead of what the code was supposed to do. He is the one that determined it was a closed issue. As he's the main lead developer, it is up to him.

**Comment by Ylmzef** [comment]
So old status updates are dump for upgraded sites and who do not want use html app.
Nice work :+1:
