### ISSUE TITLE
Privacy settings issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#407]
There no option for Anyone in privacy settings.
Also when i try hide my bday and others options these all dont working too.
I tested on community too.

![indir](https://cloud.githubusercontent.com/assets/8562514/9430935/e48655cc-4a05-11e5-8ce0-8b2d5794c1c5.png)

**Comment by Jinkers** [comment]
The reason there is no option for 'anyone' in the list is because of the websites 'Friends only Community' setting. If this is turned off, the other options will show up. As for the birthday setting being an issue, I cannot confirm this. Updates on PF community, my communiy and both my local and live dev sites.

**Comment by Ylmzef** [comment]
Click update than you can see your profile secret for others and u cant undone it.

**Comment by Ylmzef** [comment]
Still waiting for this.
It's important bug too.

**Comment by Data66PF** [comment]
I can't reproduce this. I changed the site to Friends Only and saved the profile privacy so it all showed Friends Only. Then, I changed the site to No for Friends Only. I went back to my profile and changed various privacy settings to Anyone. I saved it and it saved fine. I also set the birthday not to show and it works fine.

**Comment by Ylmzef** [comment]
Facebook also Friends Only community too, but if you set your profile for everyone than your profile public for anyone.
I think you don't know this logic.
And it was so on v3.

**Comment by Data66PF** [comment]
I know the logic. Thanks. I just also see that I can't reproduce this as you said the settings are not saving but they are saving for me. Thanks.

**Comment by Data66PF** [comment]
Tested again. I have my privacy set to that anyone can see my profile. I log in with a user that is not a friend and that user can see my profile. To test further, I changed it to friends only for my profile privacy and now that user cannot see my profile.

I cannot reproduce an issue as the bug is described.

**Comment by Ylmzef** [comment]
My site Friends Only community i post a status for everyone but only me friends showing the status.
There is a logic error i think..

**Comment by Data66PF** [comment]
If it is friends only community then only friends will see stuff.

**Comment by Ylmzef** [comment]
And on my site for new registered users profile showing for every one too :smile:

**Comment by Data66PF** [comment]
The feed settings have nothing to do with the profile settings.

**Comment by Ylmzef** [comment]
But there everyone option for status what have to do it?

**Comment by Ylmzef** [comment]
Still waiting answer for this issue.

**Comment by Ylmzef** [comment]
@Data66PF @RaymondBenc I'm still waiting for solution for this since 24 august

**Comment by Data66PF** [comment]
Please don't tag us for closed issues. We cannot reproduce this issue as described.

**Comment by Ylmzef** [comment]
If you can follow the issue on beter way make sure you can reproduce the issue..
