### ISSUE TITLE
Mandatory fields issue on profile edit page

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#472]
They are not mandatory on profile edit page.

![download](https://cloud.githubusercontent.com/assets/8562514/9694421/d6d6b4ce-5358-11e5-91e2-78131c5ddba6.png)

**Comment by Data66PF** [comment]
These are no longer required fields as many clients asked to remove them as required. You can have a developer change things to be required.

**Comment by Ylmzef** [comment]
Realy? Why is it required on signup than? What meaning it?

**Comment by Data66PF** [comment]
There are settings in Registration for whether to include gender, dob, etc on the registration. You can disable them and they won't then be required there. Did you mean that you want to have those fields set to not required as they are in the profile section?

**Comment by Ylmzef** [comment]
I required gender, location, gender and custom fields for registration but those are not required on profile edit.
Is this nonsense or not?

**Comment by Data66PF** [comment]
I've been thinking about this. It's about 50/50 as to what clients want. Some want required and some don't need these fields. In order to have a better solution for all, here is my idea and please say whether anyone likes it:

Instead of removing these from being required and not having any option for it we have the settings changed in admincp so that webmasters can choose which of these are required with a yes/no switch.

Gender
DOB
Location

Then, we also still allow the custom fields to stay as they are, required or not as those already have settings.

This setting would work in registration AND profile as a required field (if set to required) should always be required or it makes no sense to have it.

**Comment by one44** [comment]
Agreed

**Comment by Data66PF** [comment]
Waiting to hear from @Ylmzef to see if the idea is good or not for them too. :)

**Comment by Ylmzef** [comment]
Good idea but it's need same for custom fields too.

**Comment by Data66PF** [comment]
That's why I mentioned custom fields in my comment.

**Comment by RaymondBenc** [comment]
I've added this back for custom fields, as it states **required** when editing a custom field. Can you confirm what setting exactly is being edited to add it as a requirement on the registration form that mentions it is required?

**Comment by Data66PF** [comment]
I'm not sure what you mean. Clients, some need a site to have mandatory fields for gender, location, birthday as they used to be before. Then recently, they were changed to being not required in another bug report as some sites had turned it off in registration settings. However, for those sites, their users had errors on the profile as the script had it hard coded to need those fields but the site didn't use those fields.

Now, with these not being required, the sites that need them required can't set them required as the setting isn't there and it's crucial for those sites to have these required. I guess we need a setting to put these back as required for the sites that need them that way as they don't show in the manage custom fields area.

**Comment by Ylmzef** [comment]
When do you want fix this?

**Comment by neil96** [comment]
We created new setting user.require_basic_field (you can find this setting in admincp->settings->user->setting). Default of setting is false. If you want to these fields (gender, country and birthday) dandatory, change this setting to true.

**Comment by Ylmzef** [comment]
Thank you so much @neil96
