### ISSUE TITLE
music album is not working

### ISSUE THREAD

**Issue by lordofnos** [moxi9/phpfox#477]
there´s no option to upload a song into an album or creating an album. when using /music/album/add the album is created and by editing this album it is possible to insert songs to this album. via songupload its not possible to insert songs.

when listing albums in music index the album photo covers the title and date.

**Comment by Data66PF** [comment]
Confirmed both issues at the community but please keep issues to one per ticket so we can have our revision numbers easily referenced and so testing is easier. Thanks!

**Comment by lordofnos** [comment]
ok, so should i split the issues or do you take the whole album thing as one issue for now? ;)

**Comment by Data66PF** [comment]
You can keep it like this for now :)

**Comment by lordofnos** [comment]
the fix does not work for me... album index is chaos and its not possible to put songs in album or make album before uploading. i have uploaded all the files from the fix... do i need to do something else?

**Comment by Data66PF** [comment]
You should have probably waited for 4.0.8 to release as it looks like there are template edits. In order to see the edits on the site, after upgrading you need to run the final upgrade steps, http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ which helps get the new theme stuff, new settings if there are any, etc.
