### ISSUE TITLE
Search button issue in admincp

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#487]
This may have been raised but I cannot find it. The button to submit a search is covered by the pop up at the bottom of the page. This issue will apply to sites that have added registration criteria
![2015-09-08 17_23_13-new notification](https://cloud.githubusercontent.com/assets/13656046/9739848/f64491ea-5651-11e5-80bd-58014e0a6a3d.jpg)
 and they are searchable.

**Comment by Data66PF** [comment]
I've not been able to reproduce any issue and added a custom checkbox field with the alphabet up to M and still it doesn't cover anything for me when testing. It disappears for me one I scroll down.

**Comment by one44** [comment]
It seems to be an intermittent issue sometimes works Sometimes not  It is the verify and delete buttons etc Under the grey bar. Not a mojor issue as it is not in the members area.

**Comment by one44** [comment]
ok this is a problem in FF works fine in Explorer Edge Microsoft 10

**Comment by Data66PF** [comment]
I tested only with FF though. Odd.

**Comment by one44** [comment]
So I am not mad LOL

**Comment by Data66PF** [comment]
Oh! I got it to reproduce! I had to actually search a username that would only get a couple of users in the list. Then, when I scroll down to see the full options on the right, now the bottom navigation bar does not go away so I can't see Submit. I can now confirm this on my live development site and this is NOT an upgraded site so this issue is for any site.

**Comment by Data66PF** [comment]
https://github.com/moxi9/phpfox/commit/845ebcf390e8ed980c42284dbfa7af6bc742cec8
