### ISSUE TITLE
Automatically deletes admin account on resend email verification.

### ISSUE THREAD

**Issue by manny12** [moxi9/phpfox#49]
When i clicked resend email verification to the admin user from the admin cpanel. The admin user account is instantly deleted.

**Comment by RaymondBenc** [comment]
Is this sending an email verification to another user or to the Admin itself?

**Comment by manny12** [comment]
It was to the admin itself from the ACP

**Comment by Data66PF** [comment]
I can't reproduce this no matter what I do. 
1. I am logged in as the main admin
2. I click the checkbox to the left of my user in admincp user browse
3. At the bottom, I click to resend email verification, which does nothing at all since I'm already verified.

I tried with a second admin too, that was not logged in and he didn't delete either.

Can you provide exact steps for how you tested and are you using the latest download on your test site?

Do you see any errors or error logs?

**Comment by RaymondBenc** [comment]
Yeah, I've been trying this myself. Haven't been able to reproduce it either.
