### ISSUE TITLE
Forum attachments issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#515]
I attachted some images on forum topic.
But it's not showing on forum topic.

4.0.7 upgraded site..

update: when i edit the post after posted and update it, its showing as attachments..
But refleshing page again it's not showing anymore again.

**Comment by one44** [comment]
I often have sane problem on community site and have to add images a few times to get it to work.

**Comment by Data66PF** [comment]
Tested two methods.

1. I added an attachment and chose inline as that is my preferred method to put an image in since the user can click it to see it larger.  This does not work. Confirmed v4.0.7

2. I added an attachment image and did not choose inline and this worked fine. 

I confirm that attachments done in the inline method are not working. Also tested at community and it doesn't work there. Firefox browser, win 10.

**Comment by Ylmzef** [comment]
It's still issue. Only inline function fixed.
Cleared cache, updated counters..

**Comment by Ylmzef** [comment]
Also i've reported this on 11 Aug too
But you can't reproduce..
 https://github.com/moxi9/phpfox/issues/325

**Comment by Data66PF** [comment]
Your post from before said things that were already there, not things that were new. I tested new attachments for this one. At any rate, please open a new bug for your new issue but please be very specific with how to reproduce the issue.

**Comment by Ylmzef** [comment]
But this not new or different issue it's same as i mentioned on my post.
