### ISSUE TITLE
Add blocks to the top of the wall

### ISSUE THREAD

**Issue by cespiritual** [moxi9/phpfox#539]
Hi,

I have a client that installed one of my apps and he want to show it on the top of the wall. But both positions (2 and 4) show on the bottom of the wall. Shouln't one of this be set to the top, and the other to the bottom?

Thanks

**Comment by Data66PF** [comment]
Would be nice if we could specify "position" as we used to be able to order blocks before but with apps we've lost that ability unless we just don't know how yet but I'm sure he will respond.

**Comment by Data66PF** [comment]
Status on this please @neil96

**Comment by neil96** [comment]
This issue will be fixed in V4.3, we are finding best solution for it.

**Comment by Data66PF** [comment]
suggest looking in v3 block addons as the position setting is there. perhaps use the same method.

**Comment by optiroot** [comment]
I need this too, because if I create so much blocks and for example I want place ads between them, I can't and this is weird for customization, even because is strange that we can do this normally in the admincp and not with our blocks.

Anyway seem that other developers - I don't name them but they're famous for creating phpfox apps - have achieved this in some way; maybe with some tweaking...

**Comment by neil96** [comment]
This issue was fixed by @RaymondBenc in V 4.3.0
