### ISSUE TITLE
Invite Only Site - Invitees with email cannot login/register

### ISSUE THREAD

**Issue by NetworkCycles** [moxi9/phpfox#559]
1. Site is invite only.
2. Member invite others from Invite page with email invitation.
3. Invitees enter their email - "Enter your email below if you received an invitation to join us."
4. Enter email from invitation.
5. Site refreshes and back to the homepage - NOT signed in. ???

No invitees can signin to site.
**************
Version:  v4.0.8
Browser:  Firefox
OS:  PC
Fresh install - no modifications.

**Comment by Gatsby-PF** [comment]
Even though "Invite only" is selected, doesn't "Allow User Registration" also need to be enabled?

Even though new invites have registered, they may still be subject to and have to wait admin approval before they can login, which is yet another step above registration.

If this happens to be the case, does the message they get after registering give them the required information so that their expectation of what comes next is not confused?

**Comment by NetworkCycles** [comment]
My User Registration Settings: 

Allow User Registration – No
Verify Email At Signup – No
Captcha on Registration – Yes
Approve Users – No
Disable Username on Registration – Yes
Invite Only – Yes

Still not working as designed.

**Comment by NetworkCycles** [comment]
I think I understand now.

FIXED:  
Allow User Registration – (set to YES)

It works.

An Invite only site, must allow user registration - Set to Yes.

**Comment by NetworkCycles** [comment]
My User Registration Settings: 

Allow User Registration – No
Verify Email At Signup – No
Captcha on Registration – Yes
Approve Users – No
Disable Username on Registration – Yes
Invite Only – Yes

Still not working.

**Comment by Gatsby-PF** [comment]
Even though your site is invite only,  users responding to invites still need to register, which means Allow User Registration should be "ON". 

The invite switch then narrows the scope of what types of registration this setting allows or disallows so that if Invite Only=Yes, registration is possible only for those showing up with addresses showing a match in the sites database of invites, but not for the public in  general.

Allow User Registration would be set to 0 only if it is a closed community not permitting registrations or new members of any kind, or where Admin creates all new members internally as with a company.

**Comment by NetworkCycles** [comment]
FIXED: 
Even though your site is invite only, users responding to invites still need to register, which means Allow User Registration should be "ON" (set to YES).
