### ISSUE TITLE
Invisibility setting

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#612]
Observations:
Under "User Groups" settings for "User" has option
"If enabled, members of this user group will be able hide themselves from the Browse section when they enable "Invisible Mode" from Profile -> Privacy Settings"
Going to privacy settings there is no invisible mode setting.

Test:
So I maximally restrict all options across the board for admin test user.
Then cleared site and browser caches

Result:
Logging in as another user in registered group, test user shows up in members area,
and  was able to successfully search on the username in the search block in members area.

Administrative users should not show in public members listings, and should have at least the option to be out of site, but with full visibility of, and access to any member in any other group.

**Comment by Data66PF** [comment]
In regards to your last sentence, that would be for your site though. I want admins to show on my sites as do other clients. I think what you want is the invisibility setting enabled in the settings again as it was removed.

**Comment by Gatsby-PF** [comment]
When losing weight, there is such a thing as shedding too many pounds so as to become only a skeleton of your former self.

**Comment by Data66PF** [comment]
Well if we put it in terms of losing weight, the script was 3000 lbs. When trying to lose that amount of weight, we need to do it in a way that gets back to a healthy, manageable weight so that if we want to ride the bus, we only have to purchase one ticket as opposed to having to purchase 4 to fit our massive size. 

In correlation to the script:

The script was too large and causing issues on servers for lower end servers. It needed to be trimmed considerably without losing the main functionality so that clients could easily run it on low end and then as it grew, they could then expand. This allows for the site to function as it should and for lower costs to be realized at first, when they are needed.

Since many, many settings were there before, then many, many were removed. However, they were not deleted. They were just turned off. This left it so that sites, such as yours, could have apps made to enable all of the heavier settings and get multiple servers to accommodate the heavier settings as each setting is adding load to your site. 

This one is marked a bug to see what the developer that is assigned to it will fix (either remove the setting from the user group settings so a developer can then make an app to enable the settings without bulking up the core) or they will enable the setting in the script.

**Comment by Gatsby-PF** [comment]
You are correct, bloat is never good. Sometimes designers run every bell and whistle they can imagine to make their creation attractive to buyers, but with a downside.

The whole thing that triggered this discussion was the fact that there is a particular class of admin group user who is to stay out of site and only log in when it is time to give some perp the hatchet job (with and avatar that makes the grim reaper do a double take).  So now I find this user is featured by the system as a recommended user for others to socialize with. It is one of those situations where you can hold a very wide grin while simultaneously shaking your head no.

**Comment by Data66PF** [comment]
Ouch and gee. Well this one is kept open for a core dev to look at. Since it's also a privacy issue and some sites want invisibility, I'm sure something will be worked out. Not sure what. Hopefully, they will determine that it won't bloat things up.

**Comment by phpfoxdev** [comment]
Fixed, will be released in next version.

**Comment by Data66PF** [comment]
Fixed in v4.0.10 *staff note YPFOXNEUTRON-71 *
