### ISSUE TITLE
Cover Reposition Not Working [4.0.9]

### ISSUE THREAD

**Issue by pootato** [moxi9/phpfox#641]
Cover photos on Pages are images and should be background-images.

When clicking Reposition, it should call a jquery function that allows the user to move background-position-y and a Save Button that saves position.

If not, the feature should be removed and force the user to upload a fixed size. (to prevent stretching)

**Comment by Data66PF** [comment]
The cover images need to be the same size as fb standard cover images. 

Please file feature requests at the community forum if you want this process changed as far as the size is concerned.

As for the issue of reposition not working, I can confirm that the bug that was fixed #587 seems not to have been saved in the Git files or something as the fix is not working.

**Comment by Data66PF** [comment]
Reposition issue Fixed in v4.1.0 *staff note YPFOXNEUTRON-84 *
