### ISSUE TITLE
Banned users can still access to site.

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#665]
On my upgraded site users can still access to site.

**Comment by Data66PF** [comment]
Can they log in or just see the site? 

Are they logging in to the banned user account or a new account? If a new account, did you manually add the details to the ban filters for the email, username, user email, IP address?

**Comment by Ylmzef** [comment]
I banned a user on site and it's moved to banned usergroup.
They can log in and upload photos etc like as normal users.

**Comment by Data66PF** [comment]
Testing an upgraded site with no addons. This site was upgraded following the upgrade routine fully. I ban a user in the AdminCP search. I then try to log in as the banned user and cannot as I see the message "you have been banned from the site".

This site has no apps installed. Default neutron theme. Please ensure that for your site you upgraded by following the upgrade routine when you went from v3 to v4 as the routine was required in order to get the user passwords properly. 

Please ensure that you have no apps installed that would be for logging in such as social log in apps or sms captcha or anything like that and please test without those enabled. Please be sure the user is not a different user that used the same user name. 

Please ensure that you did not delete the user after banning them as that would delete the ban too. You need to manually add the user to the email, ip ban, username ban, etc if you want to delete a banned user and still have them banned.
