### ISSUE TITLE
Module layout issue

### ISSUE THREAD

**Issue by rajeevswe** [moxi9/phpfox#683]
I have two module like teacher and student here what i want
every html code would be different from each other suppose

default template is assign on teacher module and another template i
already have install after changes it means new one so how can i assign
newly template only for student module.

Here i am using phpfox-V4

Thanks,
Rajeev.

**Comment by Data66PF** [comment]
As I can't find the other bug report, I'll mark this confirmed though I think it is the new design.

I can confirm that template overrides are not working even on default core modules. I don't know if there is a new process for this so I've marked it confirmed and major since most want to customize their modules.

**Comment by RaymondBenc** [comment]
Template overrides have been removed in v4 modules. We are looking into brining this back.
