### ISSUE TITLE
No Scroll in V4.09 does not work Wisteria Theme Issue

### ISSUE THREAD

**Issue by ASNLifestyle** [moxi9/phpfox#692]
When I try to scroll through the items on the left home, request, notifications, etc. it will not scroll down at all.

**Comment by Data66PF** [comment]
Please state what OS and browser as I am not seeing any issue with scrolling.

**Comment by one44** [comment]
try to update them.

**Comment by ASNLifestyle** [comment]
OS WIN 10 - browser Edge, Chrome, Firefox, all up to date. How would you update theme?

**Comment by ASNLifestyle** [comment]
ok got it to work on another theme. Scroll does not work in Wisteria.

**Comment by PhpFoxJohnJr** [comment]
I use that theme as well....no scroll bar either.  ASNLifestyle....do you have the PAGES menu on the your mobile version of wisteria...only asking since you are the only other person I know using that theme.

**Comment by ASNLifestyle** [comment]
It works on the mobile version

**Comment by one44** [comment]
I use wisteria and version 4.0.9 but it is a css issue and you need to upgrade theme.

**Comment by Data66PF** [comment]
As it seems to be an issue that the theme wasn't upgraded, this will be closed. Please note to follow all of the steps in this http://scripttechs.com/article/354/phpfox-v4-upgrade-final-steps-you-need-to-do/ as you need to do that each time you upgrade, for now. The process is being looked at though.

**Comment by PhpFoxJohnJr** [comment]
Sorry SNLifestyle...I got confused.  I just checked and I do have the PAGES menu on the wisteria theme.  I guess it comes back to the missing menu for PAGES when you are not log in.  I just checked community.phpfox.com and the issue is there as well.  We their is a bug open for this already...sorry about the confusion.  Anyways if Data's final steps after upgrade does not work then try this...

it is manual but it worked for me in regards to the scroll bar.

https://github.com/moxi9/phpfox/commit/df8f9115ba830ab94253b9319fe7a80143490698

**Comment by Jinkers** [comment]
@ASNLifestyle, as stated by @one44, you need to sync the theme again (I'm another user of the Wisteria theme). To do so, go to your AdminCP->Themes->Click Wisteria -> Select the flavour you are using -> under the flavour dropdown, you will see a bunch of links-> Click the 'Sync CSS' one and let it run.

Afterwards, do a cache clear on both your PF install and your browsers and the problem should be resolved.
