### ISSUE TITLE
Profile page Pages block issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#726]
https://github.com/moxi9/phpfox/issues/425#issuecomment-157773013

It's now fixed but now when i click on the numbers it's closing the block not forwarding to all pages.

**Comment by Data66PF** [comment]
Confirmed at the community. Go to a profile that has Liked/Joined pages and groups. It has the block on there showing the pages and groups with a title and the number of pages/groups the person Likes/Joined. Click the number expecting to see the rest of the pages/groups. Instead of seeing all of their pages/groups (as the block only displays a certain amount), it closes the block. The number shown should either open a popup to show the full list or go to the user's profile section for pages/groups to see the full list. You will need to test on a user that has joined more than 10 pages/groups.

**Comment by Data66PF** [comment]
Fixed in v4.1.0 *staff note YPFOXNEUTRON-201 *
