### ISSUE TITLE
Forum reply issue

### ISSUE THREAD

**Issue by Ylmzef** [moxi9/phpfox#769]
When i post reply on forum for a topic after posting im getting "Not a valid forum." error message but the reply posted wel.

*Upgraded site
*Chrome
*Windows 10

**Comment by Data66PF** [comment]
Is the site English or another language? If you use another language, does it work with English?

**Comment by Ylmzef** [comment]
I have 4 languages but English is default language.

**Comment by Data66PF** [comment]
Ok are the threads that don't work posted in English? I had seen a bug before that things worked in English but not in another language. Just trying to rule that out as an issue.

**Comment by Ylmzef** [comment]
It's working in English not tested with other languages.

**Comment by Data66PF** [comment]
I'm going to confirm this for testing as our 4.0.10 is not throwing us out of the forum when replying. Our 4.1.0 in all of my tests is throwing us out of the forum thread once we reply. You can see the difference when replying to a post at the community, you stay in the thread after. If you test on a 4.1.0 site, after replying you are thrown out of the thread.

**Comment by Optiroot** [comment]
I confirm this too.

I add some things: if an user has Forum Moderations and edits the title or the body of a thread, 1 time on 5 the user gets "this is not a valid forum", even if it is!

And at the reply, at me not only shows the error, but sometimes I get thrown as Data66 at another thread or at the forum home (website.com/forum).

It's a really big problem, because forums are an integrant and really important part of my Community.

**Comment by Vivian-phpFox** [comment]
Fixed on 4.1.1
