### ISSUE TITLE
Bootstrap Theme cannot change header height

### ISSUE THREAD

**Issue by aakash83** [moxi9/phpfox#787]
I tried many times to  change header height from admin panel ( edit theme) but  it don't work . I cleared cache even i deleted all cache files from ftp  but it don't work.
Using chrome with latest phpfox version.

**Comment by Optiroot** [comment]
Go in CSS section; and use this if you want to change the header only height:
`div.sticky-bar { height: 200px }`
If for you doesn't work, use !important.

If you want to edit the height of the header, menu included:
`div#section-header { height: 200px }`
If doesn't work, use !important.

Then, just because of a bug, you need to sync CSS using the button in the theme options or you'll screw up your layout.

**Comment by neil96** [comment]
Fixed on V4.2.0

**Comment by Vivian-phpFox** [comment]
Do not allow to change height of the header on bootstrap theme, we removed this setting
