### ISSUE TITLE
Short URL Problem

### ISSUE THREAD

**Issue by raviji** [moxi9/phpfox#837]
Hi,

I have used 4.1.1 version and checked short url and its not working. Please make this easy way from admin side such as one click, so that backend code have to do all itself.

**Comment by Data66PF** [comment]
Cannot reproduce in 4.1.1.

**Comment by raviji** [comment]
Okay then can we have fixed this at least in 4.1.2?

**Comment by Data66PF** [comment]
Since I cannot reproduce any issue, there is nothing to fix. It is most likely a server issue with setting conflicts. Please see forum posts at our community in order to troubleshoot your server or please move to a host such as http://phpfoxsolutions.com that does not have any issues with short urls.
