### ISSUE TITLE
Share a Link Feature Not Visible In V4

### ISSUE THREAD

**Issue by DaveN21** [moxi9/phpfox#893]
I've tried to find a solution to this everywhere. 
Data (love your work very much), you say it isn't a feature anymore in V4 but in one instance it seemed to be hidden in some db features. 
Just really need to know if I can reinstate the same functions (buttons) in V4 like it shows in V3 Nebula via Admin or any other way. 
Much appreciated with any help.

![sharelinks](https://cloud.githubusercontent.com/assets/10481337/12063007/ed66fd9e-affa-11e5-9bee-1b48e643b8f2.png)

**Comment by Data66PF** [comment]
Actually, this really shouldn't have been posted as a bug since it's a feature request or question. The issue tracker is for bugs that cause the script not to work.

**Comment by Data66PF** [comment]
http://scripttechs.com/article/358/how-to-get-the-status-share-box-back-in-phpfox-v4/ this tutorial has helped others with customizing things in neutron theme. Perhaps that will help you with your issue.

**Comment by DaveN21** [comment]
Hi @Data66PF, thank you for your tip. 
Was wondering is this an official edit to the code, as I know it may void the warranty, coming from you?
Is it just best to upgrade V3 to V4 and develop that? As we are just really getting underway, should we start with the new version?
Thank you again for all your help.

**Comment by Data66PF** [comment]
It's not an official one. I don't allow the status shares on my site due to security but for those that need it, I think that will work. However, we never recommend editing source if you can make a plugin for it or if you can make an app for it. That tutorial was a "quick fix" for those that asked for it. Since it is not official phpFox patch/change, it would void any support when we (phpFox) opens our support desk.

Yes, if starting a new site, I would use V4.

**Comment by Data66PF** [comment]
just checked and the other status share links (other than photo) were removed from the v4 script so this is working as designed at this time and would take a feature request to bring it back. Alternately, a third party developer could make an app. It's not something I would make though as I don't want the liability if someone gets hacked.

**Comment by DaveN21** [comment]
Thank you Data for your follow through. May I ask why would you remove such a great feature for social networking, "just checked and the other status share links (other than photo) were removed from the v4 script so this is working as designed at this time and would take a feature request to bring it back" 
I would of thought that people would want to share to Facebook, others etc. Can we do make a feature request for V4 (optional like in V3, AdminCP toggle) would be a great advantage, your thoughts?

**Comment by Data66PF** [comment]
Sharing to fb is not the same thing that this bug is for. This issue was raised for the status share links such as photo (which is still there), blog, etc like you show in your image. Regarding what you are asking, my buffer app works for sharing to social media sites and shortens the urls so that sites don't get banned for spamming (which can happen with an active site where lots of folks share the same link if it's not shortened) and there are other apps for social media sharing such as one by YouNet. So for that, you can use apps. The script bulk was reduced to make it lighter and to put things in apps so that clients that need them can have them via installing them and clients that don't just don't install them. It can also help get more third party developers interested in making things as they won't come and stay if there is no opportunity to earn. :)

As for status share links, that this issue was raised for, those were removed to reduce bulk and I think as a security measure as any sort of thing that allows users to post directly via embedding could cause a risk. I had something happen on one of my sites before I totally removed those myself in my v3 sites and it's why I made my Uplinks module and app. It allows quick sharing to the site via buttons/links to the site content posting areas (photo, blog, etc) and doesn't have the same risk. Also, the status share posting links as shown in your image were just comments, not content so you lose out on having that content added to your site if using those status links as it doesn't get added to blogs main section for example. 

Feature requests can be added at the forum section for feature requests if you still want these features, https://community.phpfox.com/forum/122/neutron-v4-feature-requests/ but I recommend against the status share links as you lose out on content in the site.

**Comment by DaveN21** [comment]
The support I have received by you is beyond amazing thank you Data66PF. Can you please let me know of your Uplinks module and app. We really would like a quality developer for apps/modules and support ongoing and just realised that you maybe able to help. Your support is (best in industry) to date. Whatever you can supply based on all your support would be much appreciated...thx (do you ever sleep...been thinking???)

**Comment by Data66PF** [comment]
LOL yes I sleep and thank you for your kind works. :) My app for v4 is found in your admincp >> apps section but here is the listing, https://store.phpfox.com/product/809/uplinks or if you meant buffer social share, https://store.phpfox.com/techie/u/scripttechs it's in the list there (though the list isn't complete for some reason). I have more things at my ScriptTechs site and some that I've not ported to v4 so feel free to contact me at my site if you need something. Have a good day!
