### ISSUE TITLE
Invisibility

### ISSUE THREAD

**Issue by Gatsby-PF** [moxi9/phpfox#946]
The following issue ( Invisibility setting #612 ) was fixed by phpfox-dev:
https://github.com/moxi9/phpfox/issues/612

Admincp user group "user" settings contain this setting:
Can select to be invisible?  Yes/No

I select Yes, but can find no privacy setting associated with invisibility.
How is this invisibility thing supposed to work according to this fix?

**Comment by Data66PF** [comment]
Confirmed that the invisible setting disappeared from privacy. tested 4.2 site.
Please see this v3 image of the privacy settings for the front end user invisible setting:
![invisible](https://cloud.githubusercontent.com/assets/6908282/12374889/20f18e4c-bc79-11e5-84ce-e6c0396f6745.png)

**Comment by neil96** [comment]
This issue is working fine. Please also change this user group setting to "Yes" too. "If enabled, members of this user group will be able hide themselves from the Browse section when they enable "Invisible Mode" from Profile -> Privacy Settings". 
I enable it for "registered user" on https://stage.phpfox.com/. Please test again.
![screen shot 2016-01-20 at 11 25 06](https://cloud.githubusercontent.com/assets/15936115/12439909/c1132808-bf68-11e5-9a26-f418378eacff.png)

**Comment by Gatsby-PF** [comment]
Thanks Neil96.
Okay, there were TWO invisibility settings in the same setting page, and I had the topmost selected, but overlooked the bottom most one.  After selecting it, I was able to get the privacy setting for this. One less issue on the list!
