### ISSUE TITLE
Claim Page, Share Buttons Missing

### ISSUE THREAD

**Issue by one44** [moxi9/phpfox#966]
No claim button. Like/unlike button, share button.

**Comment by one44** [comment]
has this been fixed as ref 964 does not show fixed?

**Comment by Vivian-phpFox** [comment]
Enabling "Pages Mini Menu" to see "Share" link

**Comment by one44** [comment]
Thanks for fixing.............................

**Comment by PhpFoxJohnJr** [comment]
I don't want to start another thread but I have been using Pages Mini Menu since 4.09 which like Vivian said has claim, share and now they added another in this latest fix so now I have a claim button and a like button on the bottom right corner of the cover image and for me in block 1 have Pages Mini Menu which consist of "Share" and another claim button.  So I have two claim buttons on one page...

Maybe this could be fixed later on...no rush but although it looks nice and it does having the claim button on the cover image it is only going to be click one person one time so why cover even a small portion of the image for something that may or may not be ever click or needed.  I still want it on the page but it should be on a Pages Mini Menu like you have it where claim, share and report should all be.  By the way where is the report button...did we ever have a report button on pages?

**Comment by neil96** [comment]
Could you open new issue?
